# Generated by Django 3.1.2 on 2020-12-11 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('facebook_seller', models.CharField(max_length=100)),
                ('gmail_seller', models.CharField(max_length=100)),
                ('website_seller', models.CharField(max_length=100)),
                ('mainshop_owner', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('admins', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('addrress', models.CharField(max_length=100)),
                ('shop_money', models.FloatField()),
                ('method_of_received_money', models.CharField(max_length=100)),
            ],
        ),
    ]
