# Generated by Django 3.1.2 on 2020-12-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
