# Generated by Django 3.1.3 on 2021-01-09 17:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=None, size=None)),
            ],
        ),
    ]
