<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-12-11 07:13
=======
# Generated by Django 3.1.2 on 2020-12-11 08:40
>>>>>>> 695658012f1c60ef1fac1bf0975c562088e434c6

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('is_seller', models.BooleanField(default=False)),
                ('Purchased_products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
    ]
