# Generated by Django 3.1.3 on 2020-12-11 10:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discrriptio',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=None, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
