# Generated by Django 3.0.8 on 2021-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201215_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.TextField()),
                ('message_code', models.TextField()),
            ],
        ),
    ]
