# Generated by Django 3.1.2 on 2021-01-09 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201215_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='favourite_products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
            preserve_default=False,
        ),
    ]
