# Generated by Django 3.0.8 on 2021-01-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mail_verification_is_autonticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail_verification',
            old_name='user_email',
            new_name='user_name',
        ),
    ]
