# Generated by Django 3.0.8 on 2021-01-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_person_favourite_products'),
        ('main', '0010_auto_20210109_1548'),
    ]

    operations = [
    ]
