# Generated by Django 3.1.2 on 2021-01-09 21:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20210109_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=3), default=None, size=100),
        ),
    ]
