# Generated by Django 3.1.2 on 2021-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210109_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='balance',
            field=models.FloatField(default=0.0, max_length=10000),
        ),
    ]
