# Generated by Django 3.0.8 on 2021-01-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210109_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='current_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
