# Generated by Django 3.1.2 on 2021-01-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_seller_balance'),
        ('main', '0013_seller_current_balance'),
    ]

    operations = [
    ]
