# Generated by Django 3.1.2 on 2021-01-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_20210110_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='balance',
        ),
    ]
